### ISSUE TITLE
users.filter is not a function

### ISSUE THREAD

**Issue by cfairweather** [codeformuenster/slackin-docker#4]
I'm receiving this error when running the docker image from https://hub.docker.com/r/chk1/slackin/

```
[slackin-1]2016-06-30T04:12:45.308023669Z /usr/local/lib/node_modules/slackin/node/slack.js:96 
[slackin-1]2016-06-30T04:12:45.308050223Z         users = users.filter(function (x) { 
[slackin-1]2016-06-30T04:12:45.308066805Z                       ^ 
[slackin-1]2016-06-30T04:12:45.308070267Z  
[slackin-1]2016-06-30T04:12:45.308073598Z TypeError: users.filter is not a function 
[slackin-1]2016-06-30T04:12:45.308077136Z     at SlackData.onres (/usr/local/lib/node_modules/slackin/node/slack.js:96:23) 
[slackin-1]2016-06-30T04:12:45.308080863Z     at /usr/local/lib/node_modules/slackin/node/slack.js:61:17 
[slackin-1]2016-06-30T04:12:45.308085160Z     at Request.callback (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:746:30) 
[slackin-1]2016-06-30T04:12:45.308090254Z     at Request.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:135:10) 
[slackin-1]2016-06-30T04:12:45.308094398Z     at emitOne (events.js:77:13) 
[slackin-1]2016-06-30T04:12:45.308097590Z     at Request.emit (events.js:169:7) 
[slackin-1]2016-06-30T04:12:45.308100988Z     at Stream.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/index.js:938:12) 
[slackin-1]2016-06-30T04:12:45.308104899Z     at emitNone (events.js:72:20) 
[slackin-1]2016-06-30T04:12:45.308108237Z     at Stream.emit (events.js:166:7) 
[slackin-1]2016-06-30T04:12:45.308111652Z     at Unzip.<anonymous> (/usr/local/lib/node_modules/slackin/node_modules/superagent/lib/node/utils.js:124:12)
```

The stack is (in Docker Cloud `Stackfile` format):

```
slackin:
  image: 'chk1/slackin:latest'
  environment:
    - HOSTNAME=slackin
    - PORT=80
    - SLACK_ORG=Xxxxxxx
    - SLACK_TOKEN=Xxxx-asdfoiasdjf-asdjfoasdjfosad------
  expose:
    - '80'
  tags:
    - nodecluster-name=slackin
```

The SLACK_ORG and SLACK_TOKEN have been working so far and have registered a couple users. What's going on here?! ¯_(ツ)_/¯ 

Thanks!
